version: '3.3'

services:
  btcd:
    image: btcsuite/btcd:latest
    container_name: btcd
    hostname: btcd
    command:
      - btcd
      - --simnet
      - --rpcuser=user
      - --rpcpass=pass
      - --rpclisten=0.0.0.0:18556       # port rpc
      - --listen=0.0.0.0:18555          # reseau P2P
      - --debuglevel=debug
      - --txindex
      # address récompense de minage pour la génération de bloc auto en simnet
      #       lncli --network=simnet newaddress np2wkh
      - --miningaddr=sb1q86m66vgfj2f600fap8e28hpk7c0ezkcvruhsnh
    ports:
      - "18556:18556"
      - "18555:18555"
    volumes:
      - btcd_data:/root/.btcd

  lnd1:
    image: lightninglabs/lnd:v0.19.3-beta.rc2
    container_name: lnd1
    hostname: lnd1
    depends_on:
      - btcd
    command:
      - lnd
      - --btcd.rpchost=btcd:18556
      - --bitcoin.active
      - --bitcoin.simnet
      - --bitcoin.node=btcd
      - --btcd.rpcuser=user
      - --btcd.rpcpass=pass
      - --listen=0.0.0.0:9735                       # reseau P2P pour le connect
      - --debuglevel=trace
      - --watchtower.active
      - --watchtower.externalip=lndtower:9911
      - --rpclisten=0.0.0.0:10009                   # exposition du port à l'extérieur
      - --externalip=lnd1:10009                     # uris pour le getinfo

    ports:
      - "10009:10009"
      - "9735:9735"
    volumes:
      - lnd1_data:/root/.lnd
      - btcd_data:/root/.btcd       # pour avoir le certificat de btcd

  lnd2:
    image: lightninglabs/lnd:v0.19.3-beta.rc2
    container_name: lnd2
    hostname: lnd2
    depends_on:
      - btcd
    command:
      - lnd
      - --btcd.rpchost=btcd:18556
      - --bitcoin.active
      - --bitcoin.simnet
      - --bitcoin.node=btcd
      - --btcd.rpcuser=user
      - --btcd.rpcpass=pass
      - --listen=0.0.0.0:9735
      - --debuglevel=info
      - --watchtower.active
      - --watchtower.externalip=lndtower:9911
      - --rpclisten=0.0.0.0:10009
      - --externalip=lnd2:10009

    ports:
      - "10010:10009"
      - "9736:9735"
    volumes:
      - lnd2_data:/root/.lnd
      - btcd_data:/root/.btcd

  lndtower:
    image: lightninglabs/lnd:v0.19.3-beta.rc2
    container_name: lndtower
    hostname: lndtower
    command:
      - lnd
      - --bitcoin.simnet
      - --watchtower.active
      - --listen=0.0.0.0:9911
      - --debuglevel=info
      - --bitcoin.node=btcd
      - --btcd.rpcuser=user
      - --btcd.rpcpass=pass
      - --rpclisten=0.0.0.0:10009
      - --externalip=lnd2:10009
    ports:
      - "9911:9911"
    volumes:
      - tower_data:/root/.lnd

volumes:
  btcd_data:
  lnd1_data:
  lnd2_data:
  tower_data:
