version: '3.8'

services:
  btcd:
    image: btcsuite/btcd:latest
    command: >
      btcd --simnet --rpcuser=user --rpcpass=pass
           --rpclisten=0.0.0.0:18334 --listen=0.0.0.0:18555
           --debuglevel=debug --txindex
    ports:
      - "18334:18334"
      - "18555:18555"
    volumes:
      - btcd_data:/root/.btcd

  lnd1:
    image: lightninglabs/lnd:latest
    depends_on:
      - btcd
    command: >
      lnd --simnet --rpchost=btcd:18334 --bitcoin.active
          --bitcoin.node=btcd --bitcoin.rpcuser=user --bitcoin.rpcpass=pass
          --listen=0.0.0.0:9735 --debuglevel=info
          --watchtower.active --watchtower.externalip=lndtower:9911
    ports:
      - "10009:10009"
      - "9735:9735"
    volumes:
      - lnd1_data:/root/.lnd

  lnd2:
    image: lightninglabs/lnd:latest
    depends_on:
      - btcd
    command: >
      lnd --simnet --rpchost=btcd:18334 --bitcoin.active
          --bitcoin.node=btcd --bitcoin.rpcuser=user --bitcoin.rpcpass=pass
          --listen=0.0.0.0:9736 --debuglevel=info
          --watchtower.active --watchtower.externalip=lndtower:9911
    ports:
      - "10010:10009"
      - "9736:9735"
    volumes:
      - lnd2_data:/root/.lnd

  lndtower:
    image: lightninglabs/lnd:latest
    command: >
      lnd --simnet --watchtower.active --listen=0.0.0.0:9911
           --debuglevel=info
    ports:
      - "9911:9911"
    volumes:
      - tower_data:/root/.lnd

volumes:
  btcd_data:
  lnd1_data:
  lnd2_data:
  tower_data: