

services:
  backend:
    image: LMare/lightning-playground-backend:${APP_VERSION}
    hostname: backend
    volumes:
      - lnd-0_data:/app/node-storage/lnd-0
      - lnd-1_data:/app/node-storage/lnd-1

  frontend:
    image: LMare/lightning-playground-frontend:${APP_VERSION}
    hostname: frontend
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  btcd:
    image: btcsuite/btcd:${BTCD_VERSION}
    hostname: btcd
    command:
      - btcd
      - --simnet
      - --rpcuser=user
      - --rpcpass=pass
      - --rpclisten=0.0.0.0:18556       # port rpc
      - --listen=0.0.0.0:18555          # reseau P2P
      - --debuglevel=debug
      - --txindex
      # address récompense de minage pour la génération de bloc auto en simnet
      #       lncli --network=simnet newaddress np2wkh
      - --miningaddr=rneZnvYmrLg9V6seGghNXmdfzatNsHgb54
    volumes:
      - btcd_data:/root/.btcd
      - ./btcd.conf:/root/.btcd/btcd.conf   # To simplify the cmd btcctl

  lnd-0:
    image: LMare/lnd:${LND_TAG}
    hostname: lnd-0.lnd-headless.lightning-playground.svc.cluster.local
    depends_on:
      - btcd
    command:
      - lnd
      - --btcd.rpchost=btcd:18556
      - --bitcoin.active
      - --bitcoin.simnet
      - --bitcoin.node=btcd
      - --btcd.rpcuser=user
      - --btcd.rpcpass=pass
      - --listen=0.0.0.0:9735                       # reseau P2P pour le connect
      - --debuglevel=trace
      - --watchtower.active
      - --watchtower.externalip=lndtower:9911
      - --rpclisten=0.0.0.0:10009                   # exposition du port à l'extérieur
      - --externalip=lnd-0.lnd-headless.lightning-playground.svc.cluster.local:9735 # uris pour le getinfo
      - --tlsextradomain=lnd-0.lnd-headless.lightning-playground.svc.cluster.local  # domaine pour le certificat
    volumes:
      - lnd-0_data:/root/.lnd
      - btcd_data:/root/.btcd       # pour avoir le certificat de btcd

  lnd-1:
    image: LMare/lnd:${LND_TAG}
    hostname: lnd-1.lnd-headless.lightning-playground.svc.cluster.local
    depends_on:
      - btcd
    command:
      - lnd
      - --btcd.rpchost=btcd:18556
      - --bitcoin.active
      - --bitcoin.simnet
      - --bitcoin.node=btcd
      - --btcd.rpcuser=user
      - --btcd.rpcpass=pass
      - --listen=0.0.0.0:9735
      - --debuglevel=info
      - --watchtower.active
      - --watchtower.externalip=lndtower:9911
      - --rpclisten=0.0.0.0:10009
      - --externalip=lnd-1.lnd-headless.lightning-playground.svc.cluster.local:9735
      - --tlsextradomain=lnd-1.lnd-headless.lightning-playground.svc.cluster.local    # domaine pour le certificat
    volumes:
      - lnd-1_data:/root/.lnd
      - btcd_data:/root/.btcd

  lndtower:
    image: LMare/lnd:${LND_TAG}
    hostname: lndtower
    command:
      - lnd
      - --bitcoin.simnet
      - --watchtower.active
      - --listen=0.0.0.0:9911
      - --debuglevel=info
      - --bitcoin.node=btcd
      - --btcd.rpcuser=user
      - --btcd.rpcpass=pass
      - --rpclisten=0.0.0.0:10009
      - --externalip=lndtower:9735
    volumes:
      - tower_data:/root/.lnd

volumes:
  btcd_data:
  lnd-0_data:
  lnd-1_data:
  tower_data:
