# Deployement of pod backend in stateless
apiVersion: apps/v1
kind: Deployment  # -> des pods stateless, on scale facilement
metadata:
  annotations:
    version : 0.2.0-SNAPSHOT
    author: LMare
  labels:
    app: backend
  name: backend
  namespace : lightning-playground
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: backend-service-account
      volumes:
        - name: lnd-shared-data
          emptyDir: {}
      containers:
        - name: backend
          image: LMare/lightning-playground-backend:v0.2.0-SNAPSHOT
          name: backend
          ports:
            - name: backend-port
              containerPort: 8080
          volumeMounts:
            - name: lnd-shared-data
              mountPath: /app/nodes-storage

        - name: sidecar
          image: LMare/sidecar-backend:v0.1.0
          volumeMounts:
            - name: lnd-shared-data
              mountPath: /app/nodes-storage

      restartPolicy: Always
