# StatefulSet pod for btcd
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: btcd
  name: btcd
  namespace : lightning-playground
spec:
  serviceName: btcd-headless  # to give the unique url for each pod
  serviceAccountName: btcd-service-account
  replicas: 1
  selector:
    matchLabels:
      app: btcd
  template:
    metadata:
      labels:
        app: btcd
    spec:
      containers:
        - name: btcd
          env:
            - name: MINING_ADDR
              value: rneZnvYmrLg9V6seGghNXmdfzatNsHgb54
          args:
            - btcd
            - --simnet
            - --rpcuser=user
            - --rpcpass=pass
            - --rpclisten=0.0.0.0:18556
            - --listen=0.0.0.0:18555
            - --debuglevel=debug
            - --txindex
            - --miningaddr=$(MINING_ADDR)
          image: btcsuite/btcd:v0.25.0
          name: btcd
          volumeMounts:
            - mountPath: /root/.btcd
              name: btcd-data
            - mountPath: /root/.btcd/btcd.conf
              name: btcd-cm1
              subPath: btcd.conf
          ports:
            - name: grpc-port
              containerPort: 18556
            - name: p2p-port
              containerPort: 18555

        - name: sidecar
          image: LMare/sidecar-btcd:v0.1.0
          volumeMounts:
            - name: btcd-data           # to read the certs & sent to Secret Bundle BTCD
              mountPath: /root/.btcd

      restartPolicy: Always
    volumeClaimTemplates:
      metadata:
        name: btcd-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Mi # Sould be enought in simnet
