# ServiceAccount for the sidecar
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lnd-secret-writer
  namespace: lightning-playground
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lnd-secret-reader
  namespace: lightning-playground
