version: 3

config:
  PREFECT_API_URL: http://prefect-server.data.svc.cluster.local:4200/api

deployments:
  - name: simnet
    entrypoint: flows/flows.py:elt_master_flow
    work_pool:
      name: mon-pool-k8s
    work_dir: /opt/prefect
    pull: []
    flow_run_start_dir: /opt/prefect/flows
    build: []
