apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    app: btcd
  name: btcd-config-map
  namespace: lightning-playground
data:
  btcd.conf: |+
    rpcuser=user
    rpcpass=pass
    rpcserver=localhost:18556
    rpccert=/root/.btcd/rpc.cert
    simnet=1
